### ISSUE TITLE
Documentation nits

### ISSUE THREAD

**Issue by andk** [augensalat/mojolicious-plugin-sizelimit#1]
Maybe it would be good to make the documentation more concise in a few places.

(1) there is the ABSTRACT and the headline 'Kill Your Children If They Grow Too Large'. Given that there is no kill() call in the code I think the allegoric language is misleading. If the thing works as intended, there is no kill involved, right?

(2) There is this sentence: 'if it exceeds a threshold, exits gracefully'. As far as I can see, it calls Mojo::IOLoop->singleton->stop_gracefully. Luckily, this is a documented method and so I would recommend documenting just that. Since I see no consensus definition of know what "gracefully" actually means, it probably pays off to be pedantic in the docs.

(3) There is this sentence: 'Since Perl does not give memory back to the system after using it'. This is not universal. The correct statement goes more like: You can't rely on memory being returned to the system, but it can happen (see http://www.perlmonks.org/?node_id=803515) Or mayeb even: stay tuned about how much giving back of memory is doable with the right tools.

**Comment by augensalat** [comment]
Fixed in b595f57 and ce156c1
