### ISSUE TITLE
Wishlist: Startup message, Startup sanity check

### ISSUE THREAD

**Issue by andk** [augensalat/mojolicious-plugin-sizelimit#2]
I'd find it nice to have a startup message when SizeLimit gets loaded. It would help verifying that all is in the state I want it to have. Something like

SizeLimit version xxx loaded. Will assert size stays below xxx every xxx requests. Current size is xxx.

If there are users who are allergic against start up messages, they could get an inhibit_startup_message switch.

I would also find a fatal error useful if the process size at startup is already above the desired size. The user story for this could be that somebody has a working configuration but some change in his code makes the process bigger from one release to the next. They should probably get an early fail. If people are allergic against this fatal error, they could get an inhibit_startup_sanity check switch.

What Do You Think?

**Comment by wsdookadr** [comment]
@andk @augensalat please have a look at #6 , it's meant to address this issue

**Comment by augensalat** [comment]
I decided not to implement anything like this.
- I do not see the benefit of such a log message. There are smarter ways to check your installed modules.
- This plugin addresses the problem when a process grows to big over time. But who wants to terminate a program at the very beginning, which makes it completely useless? Either fix your code before release or buy some RAM!

**Comment by andk** [comment]
Unfortunately, I cannot remember the details that prompted me to file this issue.  So I feel unable to argue over it at the moment. It's a pity I didn't describe the problems in a more compelling way. Maybe I'll reopen the issue when I remember the details some day. But don't hold your breath! Cheers,
