### ISSUE TITLE
Test suite fails (with Mojolicious 6.54 and later)

### ISSUE THREAD

**Issue by eserte** [augensalat/mojolicious-plugin-sizelimit#4]
t/basic.t started to fail recently:

```
#   Failed test '200 OK'
#   at t/basic.t line 60.
#          got: undef
#     expected: '200'

#   Failed test 'exact match for content'
#   at t/basic.t line 60.
#          got: ''
#     expected: '6820'

#   Failed test 'Connection: close'
#   at t/basic.t line 60.
#          got: undef
#     expected: 'close'
# plugin 'SizeLimit', max_unshared_size => '17745', check_interval => 2;
# current size = 35728, shared = 2
# Looks like you failed 3 tests of 11.
t/basic.t ...... 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/11 subtests 
```

Statistical analysis suggests that the problem is caused by recent Mojolicious versions (negative theta is "bad"):

```
****************************************************************
Regression 'mod:Mojolicious'
****************************************************************
Name                   Theta          StdErr     T-stat
[0='const']           1.0000          0.0000    10900136809476882.00
[1='eq_6.26']         0.0000          0.0000       0.43
[2='eq_6.27']         0.0000          0.0000       0.96
[3='eq_6.29']         0.0000          0.0000       2.74
[4='eq_6.31']        -0.0000          0.0000      -0.46
[5='eq_6.32']         0.0000          0.0000       0.00
[6='eq_6.34']        -0.0000          0.0000      -1.83
[7='eq_6.35']         0.0000          0.0000       0.46
[8='eq_6.37']         0.0000          0.0000       0.00
[9='eq_6.38']         0.0000          0.0000       0.00
[10='eq_6.41']        0.0000          0.0000       0.00
[11='eq_6.47']        0.0000          0.0000       3.03
[12='eq_6.54']       -1.0000          0.0000    -5450068404738441.00
[13='eq_6.55']       -1.0000          0.0000    -4119864464922409.00
[14='eq_6.56']       -1.0000          0.0000    -9560052400295440.00

R^2= 1.000, N= 55, K= 15
****************************************************************
```

**Comment by andk** [comment]
Hallo, Bernhard, to understand the analysis, read the table: we have no tests that were run with the Mojolicious versions between 5.47 and 5.54, so any of those can be the blamespot.

You can visit the most recent version of the table at http://analysis.cpantesters.org/solved?distv=Mojolicious-Plugin-SizeLimit-0.005#mod%3AMojolicious. ATM there's no finer-grained table and if no testers sends in reports for the versions in between, the state won't improve.

**Comment by andk** [comment]
Table has improved. ATM it looks like culprit is with 6.52

**Comment by preaction** [comment]
The tests are still failing, and it seems like there are some more changes that need to be made due to changes in Mojolicious. I'm willing to make those changes, if you're available to merge and make a new release. I am also willing to adopt this module if you'd like.

**Comment by murdegern** [comment]
Do you have any news on this? I'd love to use this module (we got some hackish self-kill-with-SIGQUIT here which doesn't work so brilliantly).
The only thing I could easily fix is that slurp and spurt are now in Mojo::File and not exported, but that doesn't cut the cake.

**Comment by wsdookadr** [comment]
Hi, I've tried to address [this in PR/5](https://github.com/augensalat/mojolicious-plugin-sizelimit/pull/5), please have a look :slightly_smiling_face:

**Comment by wsdookadr** [comment]
Yeah @murdegern , it definitely seems like the maintainer of this project is unresponsive. Contacted them multiple ways, they can't find the time to maintain this project.

I have forked it and will maintain a fork of this. If you're interested in a more recent version with the bugs fixed, [my fork is here](https://github.com/wsdookadr/mojolicious-plugin-sizelimit).

**Comment by augensalat** [comment]
Release 0.006 is compatible with Mojolicious 8.02 and up.
